const games = [
  {
    "name": "Tainted Grail: Kings of Ruin",
    "bgg": 360366,
    "designer": "Awaken Realms",
    "year": 2024,
    "desc": "Standalone Arthurian dark fantasy. Streamlined from original — faster setup, clearer rules, campaign narrative with branching choices.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "Arthurian theme. Streamlined from original but still heavy on table presence. Survival elements may trigger your grind concern. Research fiddliness before buying.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Oathsworn: Into the Deepwood",
    "bgg": 251661,
    "designer": "Shadowborne Games",
    "year": 2022,
    "desc": "Narrative-heavy campaign. Storybook encounters + card-based combat (no grid). Each session is a self-contained chapter.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "No grid combat — card-based. Genuine multiplayer. But setup is heavy (minis, cards, storybook). Fiddliness ~4. Sessions run 2-3 hours.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Arydia: The Paths We Dare Tread",
    "bgg": 219650,
    "designer": "Far Off Games",
    "year": 2025,
    "desc": "Open-world cooperative RPG, no GM required. Streamlined action economy, narrative exploration, campaign progression.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "Reviewers praise streamlined mechanics and narrative depth. 'Intuitive, fresh, familiar.' No grid, no GM, no app. Now at retail. Setup still involves map/cards.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Nemesis: Retaliation",
    "bgg": 381248,
    "designer": "Awaken Realms",
    "year": 2025,
    "desc": "Standalone Nemesis sequel. New aliens, new ship, same semi-cooperative sci-fi horror. Hidden objectives, dramatic tension.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "SCI-FI. You love Nemesis (rated 9 on TTS). This is more Nemesis. Same fiddliness concerns — best on TTS. Semi-coop with hidden objectives.",
    "status": "available",
    "narrativeType": "emergent"
  },
  {
    "name": "Deep Regrets",
    "bgg": 397931,
    "designer": "Judson Cowan",
    "year": 2025,
    "desc": "Dredge-inspired solo/coop. Fish increasingly horrifying catches, manage your boat, uncover oceanic mysteries.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "Easy to table, narrative horror, opportunity luck. But solo-focused (1-2p) and has survival/resource elements. Dredge tone is unique.",
    "status": "available",
    "narrativeType": "scenario"
  },
  {
    "name": "Earthborne Rangers",
    "bgg": 342900,
    "designer": "Andrew Navaro",
    "year": 2023,
    "desc": "Cooperative card game set in a far-future wilderness where nature has reclaimed civilization. Open-world exploration, 50+ hour campaign.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": true,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "Beautiful world, genuine narrative. BUT has deck construction between sessions (building your Ranger deck). Violates your strict rubric. Otherwise perfect.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Moon Colony Bloodbath",
    "bgg": 425549,
    "designer": "Donald X. Vaccarino",
    "year": 2025,
    "desc": "Engine-building engine-DESTROYING tableau game. Build moon colonies while killer robots tear them down. From the Dominion designer.",
    "tags": {
      "cooperative": false,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": true,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "SCI-FI + engine building + Vaccarino pedigree. Easy to table, snappy turns. BUT has engine destruction (robots kill your stuff) — tests your 'no negative progress' rule. Shared deck means indirect interaction, not direct PvP.",
    "status": "available",
    "narrativeType": "emergent"
  },
  {
    "name": "Lands of Evershade",
    "bgg": 415848,
    "designer": "Leder Games",
    "year": 2026,
    "desc": "Cooperative narrative adventure from the Root publisher. Explore a dark fairy-tale world with asymmetric characters.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "Dark fairy-tale = Oz/Alice adjacent. Leder Games pedigree (Root). Asymmetric co-op. On your wishlist. Watch for fiddliness reports.",
    "status": "kickstarter",
    "narrativeType": "campaign"
  },
  {
    "name": "Horror on the Orient Express",
    "bgg": 394897,
    "designer": "Chaosium / CMON",
    "year": 2026,
    "desc": "Classic Call of Cthulhu campaign adapted to board game. Train-based horror across Europe.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. Lovecraft narrative campaign. CMON production. Fiddliness unknown — watch reviews. Train setting is unique.",
    "status": "kickstarter",
    "narrativeType": "campaign"
  },
  {
    "name": "Tales of Arabian Nights: 40th Anniversary",
    "bgg": 432392,
    "designer": "Z-Man / Eric Goldberg",
    "year": 2026,
    "desc": "Reimagined classic. Storybook adventure with branching encounters. New edition with modernized mechanics.",
    "tags": {
      "cooperative": false,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. Narrative exploration benchmark. Original had chaos/randomness concerns — watch if 40th fixes agency issues.",
    "status": "kickstarter",
    "narrativeType": "vignette"
  },
  {
    "name": "Watson & Holmes: The Lost Diaries",
    "bgg": 346142,
    "designer": "Space Cowboys",
    "year": 2026,
    "desc": "Cooperative deduction sequel. Investigate cases using tangible evidence and story context.",
    "tags": {
      "cooperative": false,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. Detective Stories = your sweet spot. You own Watson & Holmes. Easy to table. Watch for whether it's competitive or cooperative this time.",
    "status": "kickstarter",
    "narrativeType": "scenario"
  },
  {
    "name": "The Queen's Dilemma",
    "bgg": 341870,
    "designer": "Horrible Guild",
    "year": 2026,
    "desc": "Legacy negotiation game. Sequel to The King's Dilemma with campaign narrative and political intrigue.",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": true,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. Legacy narrative with group decisions. King's Dilemma is highly rated. Has negotiation/voting — not auction but social pressure.",
    "status": "kickstarter",
    "narrativeType": "campaign"
  },
  {
    "name": "Kinfire Chronicles: Night's Fall",
    "bgg": 364655,
    "designer": "Kevin Wilson",
    "year": 2023,
    "desc": "Cooperative quest-based RPG campaign. 21 quests, card-driven combat, illustrated atlas. No grid, no app.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": true,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. Easy to table, genuine co-op, narrative campaign. BUT has deck construction between quests (building your seeker deck). Same concern as Earthborne Rangers.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Vagrantsong",
    "bgg": 340325,
    "designer": "Wyrd Games",
    "year": 2022,
    "desc": "Cooperative boss-battler on a ghost train. Story-driven campaign, unique coin-flipping combat, grid-based movement.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this. Boss-battler like CDMD but with campaign narrative. Coin-flipping = opportunity luck. Easy setup. BUT uses grid combat — same concern as Gloomhaven.",
    "status": "owned",
    "narrativeType": "campaign"
  },
  {
    "name": "Mansions of Madness: Second Edition",
    "bgg": 205059,
    "designer": "FFG",
    "year": 2016,
    "desc": "App-driven Lovecraft investigation. Asymmetric investigators, narrative scenarios, no GM needed.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": true,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. App handles all fiddliness (monster AI, map reveals). BUT violates your No App rule. Grid movement. Include only if you relax those filters.",
    "status": "available",
    "narrativeType": "scenario"
  },
  {
    "name": "Unsettled",
    "bgg": 290484,
    "designer": "Orange Nebula",
    "year": 2021,
    "desc": "Cooperative sci-fi survival on alien planets. Each planet is a unique puzzle box. Asymmetric abilities.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. SCI-FI co-op with unique planet puzzles. Easy to table (each planet is self-contained). Survival elements but puzzle-focused not grind-focused.",
    "status": "available",
    "narrativeType": "scenario"
  },
  {
    "name": "Stokerverse",
    "bgg": 431169,
    "designer": "Mythic Games",
    "year": 2025,
    "desc": "Cooperative Dracula-universe game. Asymmetric hunters vs narrative campaign across gothic Europe.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist. Gothic horror co-op, asymmetric, narrative. Quick sessions (20-40 min). Watch for depth — may be too light.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Arkham Horror: The Card Game",
    "bgg": 205637,
    "designer": "FFG",
    "year": 2016,
    "desc": "Campaign LCG. Narrative agency, asymmetric investigators, chaos bag, deck progression. Your #1 game (rated 10).",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": true,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "YOUR #1. The benchmark. Deck construction between sessions is the tradeoff for campaign depth. Hard to table = setup + teardown + consistent group.",
    "status": "owned",
    "narrativeType": "campaign"
  },
  {
    "name": "T.I.M.E Stories",
    "bgg": 146508,
    "designer": "Pegasus Spiele",
    "year": 2015,
    "desc": "Cooperative time-loop narrative. Explore scenarios, die, loop back with knowledge. Unique temporal mechanic.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "YOUR #2. Easy to table, narrative, cooperative, sci-fi scenarios. The gold standard for 'grab and play' campaign narrative.",
    "status": "owned",
    "narrativeType": "scenario"
  },
  {
    "name": "Battlestar Galactica: The Board Game",
    "bgg": 37111,
    "designer": "Corey Konieczka",
    "year": 2008,
    "desc": "Semi-cooperative traitor game. Asymmetric characters, crisis management, hidden loyalty. Sci-fi drama.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "YOUR #3. Sci-fi, asymmetric, dramatic tension. Hard to table = needs 5+ players and 3 hours.",
    "status": "owned",
    "narrativeType": "emergent"
  },
  {
    "name": "Detective: A Modern Crime Board Game",
    "bgg": 223321,
    "designer": "Portal Games",
    "year": 2018,
    "desc": "Cooperative investigation. Real databases, tangible evidence, narrative cases. Your #4 game (rated 10).",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": true,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "YOUR #4. Easy to table, narrative investigation. Uses a website (not an app per se). Detective Stories = your sweet spot.",
    "status": "owned",
    "narrativeType": "scenario"
  },
  {
    "name": "Cthulhu: Death May Die",
    "bgg": 253344,
    "designer": "Rob Daviau / Eric Lang",
    "year": 2019,
    "desc": "Cooperative boss-battler. Insanity track progression, asymmetric investigators, dice-based combat. Your #5 (rated 10).",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "YOUR #5. The 'easy to table' benchmark for co-op. Grab a character, go. Scenarios feel samey (pick-up-and-deliver) but mechanics are 10/10.",
    "status": "owned",
    "narrativeType": "emergent"
  },
  {
    "name": "Nemesis",
    "bgg": 167355,
    "designer": "Awaken Realms",
    "year": 2018,
    "desc": "Semi-cooperative sci-fi horror. Hidden objectives, alien encounters, ship exploration. Your #6 (rated 9, TTS).",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "YOUR #6. Sci-fi, dramatic, asymmetric. TTS-only for you due to setup/fiddliness. Grid movement but thematic not tactical.",
    "status": "owned",
    "narrativeType": "emergent"
  },
  {
    "name": "Eldritch Horror",
    "bgg": 146021,
    "designer": "Corey Konieczka",
    "year": 2013,
    "desc": "Globe-trotting Lovecraft co-op. Asymmetric investigators, narrative encounters, round-based mythos phase.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "YOUR #7 (rated 9). Round-based fiddliness is acceptable. Hard to table = massive footprint and 3+ hours.",
    "status": "owned",
    "narrativeType": "vignette"
  },
  {
    "name": "Sleeping Gods",
    "bgg": 255984,
    "designer": "Ryan Laukat",
    "year": 2021,
    "desc": "Open-world storybook campaign. Explore a vast map, make choices, fight enemies, discover narrative threads across 20+ hours.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": true
    },
    "fit": "YOUR rated 8.5. Massive narrative exploration. TTS-only for you — stays out on table, multiplayer is one-driver. Solo/duo game in practice.",
    "status": "owned",
    "narrativeType": "campaign"
  },
  {
    "name": "The 7th Citadel",
    "bgg": 286063,
    "designer": "Ludovic Roudy / Bruno Sautter",
    "year": 2024,
    "desc": "Open-world exploration card game. Sequel to 7th Continent with improved mechanics, less grind, more narrative.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this. Improved over 7th Continent (your survival grind benchmark). Still has resource management — watch if it crosses into grind territory.",
    "status": "owned",
    "narrativeType": "campaign"
  },
  {
    "name": "Sleeping Gods: Primeval Peril",
    "bgg": 362205,
    "designer": "Ryan Laukat",
    "year": 2023,
    "desc": "Standalone Sleeping Gods sequel for 1-2 players. Tighter map, streamlined rules, prehistoric setting.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": true
    },
    "fit": "On your wishlist. Streamlined Sleeping Gods for 1-2p. Same TTS concern. Tighter experience than the original.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Robinson Crusoe: Adventures on the Cursed Island",
    "bgg": 121921,
    "designer": "Ignacy Trzewiczek",
    "year": 2012,
    "desc": "Cooperative survival adventure. Scenario-based, narrative events, tough decisions. Thematic and punishing.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this (rated 8). Narrative scenarios are great. But survival grind + fiddly rules overhead. TTS-only for you.",
    "status": "owned",
    "narrativeType": "campaign"
  },
  {
    "name": "Sherlock Holmes Consulting Detective",
    "bgg": 2511,
    "designer": "Raymond Edwards",
    "year": 1982,
    "desc": "Cooperative deduction. Read newspapers, visit locations, solve cases using tangible evidence. Zero mechanics overhead.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this (rated 8). Detective Stories benchmark. Zero setup, pure narrative investigation. The gold standard for easy-to-table narrative.",
    "status": "owned",
    "narrativeType": "scenario"
  },
  {
    "name": "Pandemic Legacy: Season 1",
    "bgg": 161936,
    "designer": "Rob Daviau / Matt Leacock",
    "year": 2015,
    "desc": "Legacy campaign cooperative. Evolving narrative, permanent changes, escalating stakes across 12-24 sessions.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this (rated 7). Easy to table, narrative campaign, genuine co-op. Benchmark for legacy games.",
    "status": "owned",
    "narrativeType": "campaign"
  },
  {
    "name": "Forgotten Waters",
    "bgg": 302723,
    "designer": "Plaid Hat Games",
    "year": 2020,
    "desc": "Cooperative pirate adventure. App-assisted storytelling with branching narrative and humor. 3-7 players.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": true,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this. Easy to table, narrative, genuine multiplayer. BUT uses an app for storytelling. Violates No App if strict.",
    "status": "owned",
    "narrativeType": "scenario"
  },
  {
    "name": "The Adventures of Robin Hood",
    "bgg": 326494,
    "designer": "Michael Menzel",
    "year": 2021,
    "desc": "Cooperative narrative adventure. Pop-up book map, hidden tokens, story-driven campaign. Family-weight.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this (rated 7). Easy to table, narrative, no app. Family-weight — lighter than your usual but charming.",
    "status": "owned",
    "narrativeType": "scenario"
  },
  {
    "name": "ISS Vanguard",
    "bgg": 325494,
    "designer": "Awaken Realms",
    "year": 2022,
    "desc": "Sci-fi campaign. Explore planets, manage crew, narrative branching. Massive scope and setup.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "app": false,
      "deckConstruction": true,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "On your wishlist (rated 8). SCI-FI campaign. But TWICE as hard to table as AHLCG — massive setup, crew deck management, ship maintenance between missions.",
    "status": "available",
    "narrativeType": "campaign"
  },
  {
    "name": "Adrift: A Puzzletale",
    "bgg": 364276,
    "designer": "Wren Games",
    "year": 2022,
    "desc": "Cooperative narrative puzzle. Solve interconnected puzzles to progress a sci-fi story. Campaign in a box.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this (rated 8). Sci-fi narrative puzzle. Easy to table. No randomness — pure puzzle solving. Unique in your collection.",
    "status": "owned",
    "narrativeType": "scenario"
  },
  {
    "name": "The Light in the Mist",
    "bgg": 341519,
    "designer": "Postmark Games",
    "year": 2022,
    "desc": "Narrative mystery in a box. Investigate a coastal town's secrets through documents, maps, and clues.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false,
      "solo": false
    },
    "fit": "You own this (rated 8.5). Detective Stories sweet spot. Easy to table, narrative investigation, no mechanics overhead.",
    "status": "owned",
    "narrativeType": "scenario"
  },
  {
    "name": "The 7th Continent",
    "bgg": 180263,
    "designer": "Ludovic Roudy / Bruno Sautter",
    "year": 2017,
    "desc": "Open-world exploration card game. Survive a cursed island across multiple sessions. Massive scope.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "You own this (rated 7). Your benchmark for survival grind — the reason you dislike the mechanic.",
    "status": "owned"
  },
  {
    "name": "Etherfields",
    "bgg": 280794,
    "designer": "Awaken Realms",
    "year": 2020,
    "desc": "Dream exploration campaign. Surreal narrative, deck-driven combat, branching dreamscapes.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "On your wishlist (rated 7). Surreal narrative is unique. But fiddly and divisive — some love it, some find it incoherent.",
    "status": "available"
  },
  {
    "name": "Charterstone",
    "bgg": 197376,
    "designer": "Jamey Stegmaier",
    "year": 2017,
    "desc": "Legacy worker placement. Build a village across 12 games, permanent changes, evolving narrative.",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "You own this (rated 7). Legacy campaign with engine building. Narrative is light but choices carry forward.",
    "status": "owned"
  },
  {
    "name": "Mice and Mystics",
    "bgg": 124708,
    "designer": "Jerry Hawthorne",
    "year": 2012,
    "desc": "Cooperative campaign. Play as mice exploring a castle. Story-driven with chapter-based progression.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "You own this (rated 7). Charming narrative but has grid combat and per-turn initiative fiddliness (your CPU Rule).",
    "status": "owned"
  },
  {
    "name": "Legacy of Dragonholt",
    "bgg": 234669,
    "designer": "Nikki Valens",
    "year": 2017,
    "desc": "Cooperative narrative RPG in a box. Choose-your-own-adventure with character progression and branching story.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": false,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "You own this. Pure narrative CYOA — no real resource management. Fails your mechanical depth test.",
    "status": "owned"
  },
  {
    "name": "Gloomhaven",
    "bgg": 174430,
    "designer": "Isaac Childres",
    "year": 2017,
    "desc": "Tactical campaign dungeon crawler. Legacy elements, branching story, 95 scenarios. TTS only for you.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "You played on TTS (rated 6). Grid combat + monster AI fiddliness. Digital version handles the CPU work.",
    "status": "owned"
  },
  {
    "name": "Frosthaven",
    "bgg": 295770,
    "designer": "Isaac Childres",
    "year": 2022,
    "desc": "Gloomhaven sequel. More narrative, town building between scenarios, 100+ scenarios.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Previously owned. Same grid combat concerns as Gloomhaven. More narrative but same core issues.",
    "status": "available"
  },
  {
    "name": "Aeon Trespass: Odyssey",
    "bgg": 242705,
    "designer": "Into the Unknown",
    "year": 2022,
    "desc": "Greek mythology campaign. Titan hunting with deep narrative branching and crew management.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Weight 4.7 — extremely heavy. Strong narrative but massive setup and fiddliness. Not easy to table.",
    "status": "available"
  },
  {
    "name": "Near and Far",
    "bgg": 195421,
    "designer": "Ryan Laukat",
    "year": 2017,
    "desc": "Adventure campaign with map exploration. Read story paragraphs at locations, worker placement between adventures.",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "On your wishlist. Same designer as Sleeping Gods. Lighter, easier to table. Mix of vignette encounters and campaign arc.",
    "status": "available"
  },
  {
    "name": "My Father's Work",
    "bgg": 328866,
    "designer": "T.C. Petty III",
    "year": 2022,
    "desc": "Legacy worker placement across 3 generations. Mad science narrative with branching story and consequences.",
    "tags": {
      "cooperative": false,
      "asymmetric": false,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": true,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "On your wishlist. Strong narrative legacy. But uses an app for story delivery and is heavy (weight 3.1).",
    "status": "available"
  },
  {
    "name": "Divinity Original Sin: The Board Game",
    "bgg": 294378,
    "designer": "Larian Studios",
    "year": 2023,
    "desc": "Video game adaptation. Open-world RPG campaign with branching narrative and tactical combat.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": true,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "On your want-to-play. Strong narrative but has grid combat AND app. Double violation.",
    "status": "available"
  },
  {
    "name": "Above and Below",
    "bgg": 172818,
    "designer": "Ryan Laukat",
    "year": 2015,
    "desc": "Village building with underground exploration. Read story encounters when you explore caves.",
    "tags": {
      "cooperative": false,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "vignette",
    "fit": "Previously owned (rated 6). Vignette encounters are fun but random. Village building is the real game.",
    "status": "available"
  },
  {
    "name": "Lands of Galzyr",
    "bgg": 281474,
    "designer": "Snowdale Design",
    "year": 2022,
    "desc": "Open-world adventure with persistent world. Encounters carry forward between sessions. Save system.",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "vignette",
    "fit": "On your wishlist. Persistent world is interesting — vignettes that remember. Easy to table. Low fiddliness.",
    "status": "available"
  },
  {
    "name": "Agents of SMERSH",
    "bgg": 111105,
    "designer": "Jason Maxwell",
    "year": 2012,
    "desc": "Cooperative spy adventure. Travel the world, read encounter paragraphs, stop a villain. Storybook game.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "vignette",
    "fit": "On your want-to-play. Spy-themed Eldritch Horror with storybook encounters. Easy to table.",
    "status": "available"
  },
  {
    "name": "Dead of Winter",
    "bgg": 150376,
    "designer": "Jonathan Gilmour",
    "year": 2014,
    "desc": "Semi-cooperative survival. Hidden traitor, crossroads cards create emergent story moments.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "emergent",
    "fit": "Previously owned (rated 7). Crossroads cards = emergent narrative. But has survival grind (feeding survivors).",
    "status": "available"
  },
  {
    "name": "Unfathomable",
    "bgg": 340466,
    "designer": "FFG",
    "year": 2021,
    "desc": "BSG spiritual successor. Hidden traitor on a sinking ship. Lovecraft theme.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "emergent",
    "fit": "You rated this 7. BSG-lite with Lovecraft skin. Easier to table than BSG (fewer players needed).",
    "status": "owned"
  },
  {
    "name": "Spirit Island",
    "bgg": 162886,
    "designer": "R. Eric Reuss",
    "year": 2017,
    "desc": "Cooperative asymmetric. Play as island spirits repelling colonizers. Powers escalate dramatically.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "emergent",
    "fit": "You own this (rated 6). Extremely asymmetric but you called it a co-op math puzzle. Kept as Gold Standard host library.",
    "status": "owned"
  },
  {
    "name": "Horrified",
    "bgg": 282524,
    "designer": "Prospero Hall",
    "year": 2019,
    "desc": "Cooperative monster hunting. Classic Universal monsters, simple rules, escalating tension.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "emergent",
    "fit": "You own this (rated 7). Easy to table, cooperative, low fiddliness. Light emergent drama from monster movement.",
    "status": "owned"
  },
  {
    "name": "Space Alert",
    "bgg": 38453,
    "designer": "Vlaada Chvatil",
    "year": 2008,
    "desc": "Real-time cooperative. Program actions simultaneously under time pressure, then resolve chaos.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "emergent",
    "fit": "You own this (rated 7). Pure emergent chaos — the story IS what went wrong. Easy to table, 30 min.",
    "status": "owned"
  },
  {
    "name": "Cozy Stickerville",
    "bgg": 456440,
    "designer": "Corey Konieczka",
    "year": 2026,
    "desc": "Cooperative legacy campaign. Build a village with 800+ stickers across 10 sessions. Branching narrative, permanent choices, Stardew Valley vibes.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "You own this (rated 8). 10-session campaign with branching story. Easy to table, cooperative, legacy choices carry forward. Corey Konieczka (BSG, Eldritch Horror designer).",
    "status": "owned"
  },
  {
    "name": "MicroMacro: Crime City",
    "bgg": 318977,
    "designer": "Johannes Sich",
    "year": 2020,
    "desc": "Cooperative visual detective game. Solve crimes by searching a massive illustrated city map for clues.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "scenario",
    "fit": "You own this (rated 8). Detective Stories sweet spot — visual searching for tangible evidence. Zero setup, grab and play.",
    "status": "owned"
  },
  {
    "name": "Detective: City of Angels",
    "bgg": 218074,
    "designer": "Evan Derrick",
    "year": 2019,
    "desc": "Noir detective investigation. Interview suspects, gather evidence, solve cases in 1940s LA. Competitive or solo.",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "scenario",
    "fit": "You rated this 8. Noir investigation with tangible evidence. Not cooperative (1 vs many or solo) but narrative investigation is your sweet spot.",
    "status": "owned"
  },
  {
    "name": "Chronicles of Crime",
    "bgg": 239188,
    "designer": "David Cicurel",
    "year": 2018,
    "desc": "App-driven detective game. Scan QR codes to investigate locations and interrogate suspects.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": true,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "scenario",
    "fit": "Previously owned (rated 4). You HATE this. App dependency removes the tactile investigation you love. QR scanning feels like busywork, not detective work.",
    "status": "available"
  },
  {
    "name": "Destinies",
    "bgg": 285192,
    "designer": "Michał Gołębiowski",
    "year": 2021,
    "desc": "Competitive narrative RPG. App-driven branching story, dice-based skill checks, race to fulfill your destiny.",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": true,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "App-driven narrative with competitive twist. Branching story is strong but app dependency is a dealbreaker for you.",
    "status": "available"
  },
  {
    "name": "Descent: Legends of the Dark",
    "bgg": 322708,
    "designer": "Kara Centell-Dunk",
    "year": 2021,
    "desc": "App-driven dungeon campaign. 3D terrain, narrative scenarios, character progression.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": true,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "App + grid combat. Double violation. Strong narrative but not for you.",
    "status": "available"
  },
  {
    "name": "Journeys in Middle-earth",
    "bgg": 269385,
    "designer": "Nathan Hajek",
    "year": 2019,
    "desc": "App-driven Lord of the Rings campaign. Explore, fight, progress characters across linked scenarios.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": true,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "App handles all fiddliness. Strong LOTR narrative. But app is required — violates your rule.",
    "status": "available"
  },
  {
    "name": "Stuffed Fables",
    "bgg": 233312,
    "designer": "Jerry Hawthorne",
    "year": 2018,
    "desc": "Cooperative storybook adventure. Play as stuffed animals protecting a child. Campaign with book-based maps.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "On your want-to-play. Charming narrative, no app. But has grid-based movement on the storybook pages.",
    "status": "available"
  },
  {
    "name": "The Isofarian Guard",
    "bgg": 281526,
    "designer": "Gamelyn Games",
    "year": 2023,
    "desc": "Cooperative narrative campaign. Branching story, character progression, tactical card combat.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Strong narrative campaign, no app, no grid. But primarily solo/duo — limited multiplayer.",
    "status": "available"
  },
  {
    "name": "Betrayal Legacy",
    "bgg": 240196,
    "designer": "Rob Daviau",
    "year": 2018,
    "desc": "Legacy campaign in a haunted house. 13 games building a multi-generational horror story.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Legacy horror campaign. Narrative carries across generations. But becomes 1-vs-many in the haunt phase (your dislike).",
    "status": "available"
  },
  {
    "name": "Clank! Legacy: Acquisitions Incorporated",
    "bgg": 266507,
    "designer": "Andy Clautice",
    "year": 2019,
    "desc": "Legacy deck-building campaign. Explore a dungeon that permanently changes across 10+ games.",
    "tags": {
      "cooperative": false,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Legacy campaign with in-game deck building (not pre-construction). Competitive push-your-luck. Narrative is humorous.",
    "status": "available"
  },
  {
    "name": "This War of Mine",
    "bgg": 188920,
    "designer": "Michał Oracz",
    "year": 2017,
    "desc": "Cooperative survival campaign. Manage civilians in a war-torn city. Brutal narrative choices.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Powerful narrative but pure survival grind. Every turn is managing hunger, sickness, depression. Your hard avoid.",
    "status": "available"
  },
  {
    "name": "Too Many Bones",
    "bgg": 192135,
    "designer": "Chip Theory Games",
    "year": 2017,
    "desc": "Cooperative dice-building RPG. Build your character through dice, fight through narrative encounters to a boss.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Highly asymmetric, dice-building progression. No grid. But fiddly (tracking dice abilities) and heavy setup.",
    "status": "available"
  },
  {
    "name": "Middara",
    "bgg": 209585,
    "designer": "Brooklynn Lundberg",
    "year": 2022,
    "desc": "Anime-inspired cooperative campaign. 100+ hour story, tactical combat, character progression.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "campaign",
    "fit": "Massive narrative scope (100+ hours). But grid combat and extremely fiddly. Not for you physically — maybe TTS.",
    "status": "available"
  },
  {
    "name": "Leviathan Wilds",
    "bgg": 358737,
    "designer": "Moon Crab Games",
    "year": 2024,
    "desc": "Cooperative boss-climbing. Scale massive creatures, coordinate with teammates, no dice combat.",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "emergent",
    "fit": "You rated this 6. Shadow of the Colossus inspired. Emergent drama from climbing mechanics. Easy to table.",
    "status": "owned"
  },
  {
    "name": "Unlock! (series)",
    "bgg": 213460,
    "designer": "Space Cowboys",
    "year": 2017,
    "desc": "Card-based escape room series. 60-minute scenarios with app for hints/verification only.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": true,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "scenario",
    "fit": "You own many and rate them 7-8. App is minimal (timer + hint system). Scenario narrative varies wildly in quality.",
    "status": "owned"
  },
  {
    "name": "Vienna Connection",
    "bgg": 299255,
    "designer": "Portal Games",
    "year": 2021,
    "desc": "Cold War detective game. Same system as Detective. Investigate espionage cases using documents and deduction.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "scenario",
    "fit": "You own this (rated 8). Same Detective system. Cold War spy narrative. Easy to table.",
    "status": "owned"
  },
  {
    "name": "Scarlet Envelope (series)",
    "bgg": 315051,
    "designer": "Postmark Games",
    "year": 2020,
    "desc": "Mail-order mystery cases. Physical documents, maps, evidence packets. Solve cases by mail.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "scenario",
    "fit": "You own many (rated 5-8.5). Detective Stories sweet spot. Physical evidence, no app. Quality varies by case.",
    "status": "owned"
  },
  {
    "name": "Hunt A Killer (series)",
    "bgg": 315954,
    "designer": "Various",
    "year": 2020,
    "desc": "Subscription mystery boxes. Physical evidence packets, solve a murder across multiple mailings.",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "engineBuild": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "narrativeType": "scenario",
    "fit": "You own several (rated 5-7). Physical evidence investigation. Quality inconsistent across boxes.",
    "status": "owned"
  }
];
