const kickstarters = [
  {
    "name": "The Witcher: Legacy",
    "bgg": 425000,
    "designer": "Go On Board / CD Projekt Red",
    "players": "1-4",
    "time": "90-120 min",
    "phase": "Late Pledge",
    "delivery": "2027",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/go-on-board/the-witcher-legacy",
    "desc": "Story-driven cooperative adventure in The Witcher universe. Branching narrative, consequences carry across sessions, 30+ hours of campaign.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Strong narrative campaign, asymmetric characters, no app. BUT has grid-based tactical combat. Cyberpunk-adjacent dark fantasy. \u20ac10.4M raised \u2014 massive community confidence."
  },
  {
    "name": "Lands of Evershade",
    "bgg": 415848,
    "designer": "Awaken Realms",
    "players": "1-5",
    "time": "90-270 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/awaken-realms/lands-of-evershade",
    "desc": "Cooperative narrative RPG/board game hybrid. Dark fairy-tale world with tactical combat and branching story. Awaken Realms storytelling.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Dark fairy-tale (Oz/Alice adjacent). Awaken Realms (Tainted Grail, Nemesis). Asymmetric co-op campaign. No app. Has tactical combat \u2014 watch for fiddliness."
  },
  {
    "name": "Horror on the Orient Express",
    "bgg": 394897,
    "designer": "CMON / Chaosium",
    "players": "1-4",
    "time": "90-120 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/cmon/horror-on-the-orient-express",
    "desc": "Classic Call of Cthulhu campaign adapted to board game. Train-based Lovecraft horror across Europe.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Lovecraft narrative campaign. CMON production quality. No app, no grid. Fiddliness unknown \u2014 CMON games tend toward heavy setup. Train setting is unique."
  },
  {
    "name": "Watson & Holmes: The Lost Diaries",
    "bgg": 346142,
    "designer": "Space Cowboys",
    "players": "1-7",
    "time": "45-90 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "Sequel to Watson & Holmes. Cooperative deduction using tangible evidence and story context.",
    "narrativeType": "scenario",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Detective Stories = your sweet spot. You own Watson & Holmes. Easy to table, no app. Watch if cooperative or competitive this time."
  },
  {
    "name": "The Queen's Dilemma",
    "bgg": 341870,
    "designer": "Horrible Guild",
    "players": "3-6",
    "time": "60-90 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "Legacy negotiation sequel to The King's Dilemma. Campaign narrative with political intrigue and group decisions.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": true
    },
    "fit": "Legacy narrative with group decisions. Has negotiation/voting (auction-adjacent). King's Dilemma is highly rated. Easy to table."
  },
  {
    "name": "Elden Ring: The Board Game",
    "bgg": 370000,
    "designer": "Steamforged Games",
    "players": "1-4",
    "time": "90-120 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/steamforged-games/elden-ring-the-board-game",
    "desc": "Open-world exploration campaign in the Lands Between. Boss fights, character builds, branching paths.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Dark fantasy campaign. But Steamforged track record is mixed (Dark Souls board game was fiddly). Grid combat likely. Wait for reviews."
  },
  {
    "name": "Nemesis: Retaliation",
    "bgg": 381248,
    "designer": "Awaken Realms",
    "players": "1-5",
    "time": "90-180 min",
    "phase": "Shipping Now",
    "delivery": "2025",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/awaken-realms/nemesis-retaliation",
    "desc": "Standalone Nemesis sequel. New aliens, new ship, same semi-cooperative sci-fi horror.",
    "narrativeType": "emergent",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "SCI-FI. More Nemesis. Room-to-room movement (not grid). Best on TTS for you due to setup. Now shipping to backers."
  },
  {
    "name": "Arkham Horror LCG: Chapter 2",
    "bgg": 463126,
    "designer": "FFG",
    "players": "1-4",
    "time": "60-120 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "New era of AHLCG. Revised core set with 4-player support, new campaign structure, streamlined deckbuilding.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": true,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "YOUR #1 GAME getting a refresh. 4-player support, streamlined. Still has deck construction. Automatic buy."
  },
  {
    "name": "Les Secrets de Warden Keene",
    "bgg": 453913,
    "designer": "Space Cowboys",
    "players": "1-4",
    "time": "20-240 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "New detective investigation game from Space Cowboys. Investigate secrets using documents and deduction.",
    "narrativeType": "scenario",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "From the Watson & Holmes / Sherlock publisher. Detective Stories sweet spot. Easy to table, no app. On your wishlist."
  },
  {
    "name": "Netherworld Candle",
    "bgg": 0,
    "designer": "Dimension Hinge",
    "players": "1-4",
    "time": "TBD",
    "phase": "Crowdfunding 2026",
    "delivery": "2027",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/dimension-hinge/netherworld-candle",
    "desc": "Chinese folk horror campaign. Fate Deck + Karma system \u2014 your greed becomes physical damage. No dice, no illusions, visceral and lethal. Massive box, English edition of a Chinese original.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Horror campaign with unique Karma mechanic (your choices hurt you). No dice \u2014 Fate Deck driven. Thematic consequences = narrative agency. Watch for fiddliness and whether Karma system feels like survival grind or meaningful tension."
  },
  {
    "name": "Netherwatch",
    "bgg": 0,
    "designer": "MJ Designs (HEXplore It)",
    "players": "1-4",
    "time": "60-90 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/hexploreit/netherwatch",
    "desc": "Cooperative horror deduction game. Investigate supernatural disturbances in cursed locations. Deduction + resource management + narrative tension.",
    "narrativeType": "scenario",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Cooperative horror deduction \u2014 Detective Stories meets haunted house. Variable player powers, no app, no grid. BUT from HEXplore It designer (known for fiddly games). Fiddliness unconfirmed \u2014 wait for reviews."
  },
  {
    "name": "Fateforge: Chronicles of Kaan",
    "bgg": 0,
    "designer": "Mighty Boards",
    "players": "1-4",
    "time": "60-120 min",
    "phase": "Pledge Manager",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/mightyboards/fateforge-chronicles-of-kaan",
    "desc": "Cooperative RPG-like board game with meaningful narrative choices and intense combat. Accessible entry point with deep campaign progression.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Cooperative narrative campaign, 1-4 players, RPG-like progression. Has grid combat (potential concern). No app. Worth investigating if combat feels tactical vs fiddly."
  },
  {
    "name": "Malhya: Lands of Legends",
    "bgg": 356731,
    "designer": "4 Univers / La Boite de Jeu",
    "players": "1-5",
    "time": "60-90 min",
    "phase": "Pledge Manager",
    "delivery": "2025",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/la-boite-de-jeu/malhya-lands-of-legends-pledge-manager",
    "desc": "Cooperative adventure game with 6 years of development. Exploration, narrative choices, and character progression across a branching campaign.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Cooperative narrative adventure, no grid combat, no app. 6 years development suggests polish. Check if mechanical depth is real or just paragraph-reading."
  },
  {
    "name": "The Eternaut",
    "bgg": 0,
    "designer": "Pendragon Game Studio",
    "players": "1-4",
    "time": "60-90 min",
    "phase": "Late Pledge",
    "delivery": "2025",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/pendragon-game-studio-srl/the-eternaut---the-board-game",
    "desc": "Narrative cooperative game based on the Argentine sci-fi comic. Survival against alien invasion with branching story and expansion content.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": true,
      "pvp": false,
      "auction": false
    },
    "fit": "Cooperative narrative survival. Sci-fi theme. No grid, no app. Has survival elements (potential grind concern). Based on a beloved comic \u2014 strong thematic source."
  },
  {
    "name": "Corps of Discovery",
    "bgg": 0,
    "designer": "Jay Cormier (Mind MGMT)",
    "players": "1-4",
    "time": "60-90 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Kickstarter",
    "url": "https://www.kickstarter.com/projects/mindmgmt/corps-of-discovery",
    "desc": "Cooperative deduction and survival game. Lewis & Clark expedition meets monsters. From the designer of Mind MGMT.",
    "narrativeType": "scenario",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": true,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "From Mind MGMT designer (strong pedigree). Cooperative deduction + survival. Low fiddle, no grid, no app. Deduction mechanic suggests meaningful decisions. Strong candidate."
  }
];
