const kickstarters = [
  {
    "name": "The Witcher: Legacy",
    "bgg": 425000,
    "designer": "Go On Board / CD Projekt Red",
    "players": "1-4",
    "time": "90-120 min",
    "phase": "Late Pledge",
    "delivery": "2027",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/go-on-board/the-witcher-legacy",
    "desc": "Story-driven cooperative adventure in The Witcher universe. Branching narrative, consequences carry across sessions, 30+ hours of campaign.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Strong narrative campaign, asymmetric characters, no app. BUT has grid-based tactical combat. Cyberpunk-adjacent dark fantasy. €10.4M raised — massive community confidence."
  },
  {
    "name": "Cyberpunk Legends: Into the Night",
    "bgg": 430000,
    "designer": "Night Crew Games",
    "players": "1-4",
    "time": "60-90 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Kickstarter",
    "url": "https://cyberpunklegends.com/",
    "desc": "Cooperative story-driven card game in a cyberpunk city. Campaign narrative with branching missions. Combat resolved by forming poker hands from your card pool.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "CYBERPUNK THEME. Cooperative campaign, no app, no grid. BUT core mechanic is forming poker hands — may feel like set collection rather than meaningful tactical decisions. Research if hand-building has enough agency for you."
  },
  {
    "name": "Lands of Evershade",
    "bgg": 415848,
    "designer": "Awaken Realms",
    "players": "1-5",
    "time": "90-270 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/awaken-realms/lands-of-evershade",
    "desc": "Cooperative narrative RPG/board game hybrid. Dark fairy-tale world with tactical combat and branching story. Awaken Realms storytelling.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Dark fairy-tale (Oz/Alice adjacent). Awaken Realms (Tainted Grail, Nemesis). Asymmetric co-op campaign. No app. Has tactical combat — watch for fiddliness."
  },
  {
    "name": "Horror on the Orient Express",
    "bgg": 394897,
    "designer": "CMON / Chaosium",
    "players": "1-4",
    "time": "90-120 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/cmon/horror-on-the-orient-express",
    "desc": "Classic Call of Cthulhu campaign adapted to board game. Train-based Lovecraft horror across Europe.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Lovecraft narrative campaign. CMON production quality. No app, no grid. Fiddliness unknown — CMON games tend toward heavy setup. Train setting is unique."
  },
  {
    "name": "Tales of Arabian Nights: 40th Anniversary",
    "bgg": 432392,
    "designer": "Z-Man / Eric Goldberg",
    "players": "1-6",
    "time": "120 min",
    "phase": "Crowdfunding 2026",
    "delivery": "2027",
    "platform": "Kickstarter",
    "url": "",
    "desc": "Reimagined classic storybook adventure. New edition with modernized mechanics and branching encounters.",
    "narrativeType": "vignette",
    "tags": {
      "cooperative": false,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": false,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Original had no mechanical depth (random paragraphs). Watch if 40th Anniversary adds real game mechanics or stays pure CYOA."
  },
  {
    "name": "Watson & Holmes: The Lost Diaries",
    "bgg": 346142,
    "designer": "Space Cowboys",
    "players": "1-7",
    "time": "45-90 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "Sequel to Watson & Holmes. Cooperative deduction using tangible evidence and story context.",
    "narrativeType": "scenario",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Detective Stories = your sweet spot. You own Watson & Holmes. Easy to table, no app. Watch if cooperative or competitive this time."
  },
  {
    "name": "The Queen's Dilemma",
    "bgg": 341870,
    "designer": "Horrible Guild",
    "players": "3-6",
    "time": "60-90 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "Legacy negotiation sequel to The King's Dilemma. Campaign narrative with political intrigue and group decisions.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": false,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": true
    },
    "fit": "Legacy narrative with group decisions. Has negotiation/voting (auction-adjacent). King's Dilemma is highly rated. Easy to table."
  },
  {
    "name": "Cthulhu: Death May Die – Season 4",
    "bgg": 374590,
    "designer": "Rob Daviau / Eric Lang",
    "players": "1-5",
    "time": "90-120 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "CMON",
    "url": "",
    "desc": "New season expansion for CDMD. New Elder Ones, new scenarios, new investigators.",
    "narrativeType": "emergent",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "More CDMD — your #5 game. New scenarios may add variety to the samey pick-up-and-deliver loop. Same great mechanics."
  },
  {
    "name": "Cthulhu: Death May Die – Forbidden Reaches",
    "bgg": 433640,
    "designer": "Rob Daviau / Eric Lang",
    "players": "1-5",
    "time": "90 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "CMON",
    "url": "",
    "desc": "Standalone CDMD expansion. New campaign-style connected scenarios with narrative progression between games.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "CDMD with CAMPAIGN NARRATIVE. Connected scenarios with progression — exactly what you said was missing. This could fix the samey problem. HIGH PRIORITY."
  },
  {
    "name": "Elden Ring: The Board Game",
    "bgg": 370000,
    "designer": "Steamforged Games",
    "players": "1-4",
    "time": "90-120 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/steamforged-games/elden-ring-the-board-game",
    "desc": "Open-world exploration campaign in the Lands Between. Boss fights, character builds, branching paths.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": true,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Dark fantasy campaign. But Steamforged track record is mixed (Dark Souls board game was fiddly). Grid combat likely. Wait for reviews."
  },
  {
    "name": "Nemesis: Retaliation",
    "bgg": 381248,
    "designer": "Awaken Realms",
    "players": "1-5",
    "time": "90-180 min",
    "phase": "Shipping Now",
    "delivery": "2025",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/awaken-realms/nemesis-retaliation",
    "desc": "Standalone Nemesis sequel. New aliens, new ship, same semi-cooperative sci-fi horror.",
    "narrativeType": "emergent",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "SCI-FI. More Nemesis. Room-to-room movement (not grid). Best on TTS for you due to setup. Now shipping to backers."
  },
  {
    "name": "Arkham Horror LCG: Chapter 2",
    "bgg": 463126,
    "designer": "FFG",
    "players": "1-4",
    "time": "60-120 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "New era of AHLCG. Revised core set with 4-player support, new campaign structure, streamlined deckbuilding.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": true,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": true,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "YOUR #1 GAME getting a refresh. 4-player support, streamlined. Still has deck construction. Automatic buy."
  },
  {
    "name": "Les Secrets de Warden Keene",
    "bgg": 453913,
    "designer": "Space Cowboys",
    "players": "1-4",
    "time": "20-240 min",
    "phase": "Pre-order 2026",
    "delivery": "2026",
    "platform": "Retail",
    "url": "",
    "desc": "New detective investigation game from Space Cowboys. Investigate secrets using documents and deduction.",
    "narrativeType": "scenario",
    "tags": {
      "cooperative": true,
      "asymmetric": false,
      "lowFiddle": true,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "From the Watson & Holmes / Sherlock publisher. Detective Stories sweet spot. Easy to table, no app. On your wishlist."
  },
  {
    "name": "Netherworld Candle",
    "bgg": 0,
    "designer": "Dimension Hinge",
    "players": "1-4",
    "time": "TBD",
    "phase": "Crowdfunding 2026",
    "delivery": "2027",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/dimension-hinge/netherworld-candle",
    "desc": "Chinese folk horror campaign. Fate Deck + Karma system — your greed becomes physical damage. No dice, no illusions, visceral and lethal. Massive box, English edition of a Chinese original.",
    "narrativeType": "campaign",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": false,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Horror campaign with unique Karma mechanic (your choices hurt you). No dice — Fate Deck driven. Thematic consequences = narrative agency. Watch for fiddliness and whether Karma system feels like survival grind or meaningful tension."
  },
  {
    "name": "Netherwatch",
    "bgg": 0,
    "designer": "MJ Designs (HEXplore It)",
    "players": "1-4",
    "time": "60-90 min",
    "phase": "Late Pledge",
    "delivery": "2026",
    "platform": "Gamefound",
    "url": "https://gamefound.com/en/projects/hexploreit/netherwatch",
    "desc": "Cooperative horror deduction game. Investigate supernatural disturbances in cursed locations. Deduction + resource management + narrative tension.",
    "narrativeType": "scenario",
    "tags": {
      "cooperative": true,
      "asymmetric": true,
      "lowFiddle": false,
      "easyTable": true,
      "mechanicalDepth": true,
      "solo": false,
      "app": false,
      "deckConstruction": false,
      "gridCombat": false,
      "survivalGrind": false,
      "pvp": false,
      "auction": false
    },
    "fit": "Cooperative horror deduction — Detective Stories meets haunted house. Variable player powers, no app, no grid. BUT from HEXplore It designer (known for fiddly games). Fiddliness unconfirmed — wait for reviews."
  }
];
